Only test some Python versions
The IRDB download keeps failing with errors like
urllib.error.ContentTooShortError: <urlopen error File was supposed to be 1450546 bytes but we only got 1450139 bytes. Download failed.>
We need to fix that, but now the CI fails most of the time